apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
      version: green
  template:
    metadata:
      labels:
        app: my-node-app
        version: green
    spec:
      containers:
      - name: my-node-app
        image: shamaanjum/my-node-app:v1
        ports:
        - containerPort: 3000
